### ISSUE TITLE
Correction request in the document

### ISSUE THREAD

**Issue by decafbad** [RegexSolver/feedback#1]
Hi. This is the author of Rust Z85 library. RegexSolver document says FAIR is encoded in Base85, but Z85 is not exactly same. Besides that, ZeroMQ's RFC doesn't support padding. You should specify as Z85 with padding.

**Comment by alexvbrdn** [comment]
Hi thank you very much for reporting this mistake. And thank you very much for your library.

I have fixed the documentation.
